# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-16 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CometCipres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
                ('newturnaroundtime', models.FloatField(blank=True, null=True)),
                ('RESULT', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comet',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GatewayCipres',
            fields=[
                ('TOOL_NAME', models.TextField(max_length=100)),
                ('TERMINATE_DATE', models.DateTimeField(primary_key=True, serialize=False)),
                ('ERROR_MSG', models.TextField(blank=True, max_length=100, null=True)),
                ('RESULT', models.SmallIntegerField(blank=True, null=True)),
                ('REMOTE_JOB_SUBMIT_DATE', models.DateTimeField(primary_key=True)),
            ],
            options={
                'db_table': 'amass_gateway_cipres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GordonCipres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_id', models.BigIntegerField(blank=True, null=True)),
                ('newturnaroundtime', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'gordon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IncaCipres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RESULT', models.SmallIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'amass_inca',
                'managed': False,
            },
        ),
    ]
